site_name: Octue Twined
site_url: https://twined.octue.com

nav:
  - Overview: index.md
  - installation.md
  - Using services:
      - using_services/getting_started.md
      - using_services/authentication.md
  - Creating services:
      - creating_services/getting_started.md
  - Managing infrastructure:
      - managing_infrastructure/getting_started.md
  - Core concepts:
      - Datafiles, datasets, and manifests:
          - core_concepts/data_containers/index.md
          - core_concepts/data_containers/datafiles.md
          - core_concepts/data_containers/datasets.md
          - core_concepts/data_containers/manifests.md
      - core_concepts/services.md
      - core_concepts/asking_questions.md
      - core_concepts/creating_services.md
  - glossary.md
  - license.md
  - version_history.md
  - support.md

theme:
  name: material
  logo: images/logos_square-dark.png
  favicon: images/logos_square-dark.png

  features:
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.copy

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - privacy
  - glightbox
  - search

copyright: Copyright &copy; 2025 Octue

extra:
  social:
    - icon: material/github
      link: https://github.com/octue
    - icon: material/linkedin
      link: https://www.linkedin.com/company/octue
    - icon: material/web
      link: https://octue.com

extra_css:
  - stylesheets/extra.css
