site_name: Octue Twined
site_url: https://twined.octue.com

nav:
  - Overview: index.md
  - installation.md
  - authentication.md
  - Getting started:
      - Using services: getting_started/using_services.md
      - Creating services: getting_started/creating_services.md
      - Managing infrastructure: getting_started/managing_infrastructure.md
  - Core concepts:
      - Datafiles, datasets, and manifests:
          - core_concepts/data_containers/index.md
          - core_concepts/data_containers/datafiles.md
          - core_concepts/data_containers/datasets.md
          - core_concepts/data_containers/manifests.md
          - More:
              - Downloading datafiles: core_concepts/data_containers/downloading_datafiles.md
              - core_concepts/data_containers/available_filters.md
      - core_concepts/services.md
      - core_concepts/asking_questions.md
      - core_concepts/creating_services.md
      - core_concepts/creating_apps.md
      - core_concepts/updating_services.md
      - core_concepts/running_services_locally.md
      - Deploying services: core_concepts/deploying_services.md
      - core_concepts/testing_services.md
      - core_concepts/troubleshooting_services.md
      - core_concepts/troubleshooting_infrastructure.md
      - core_concepts/logging.md
      - core_concepts/inter_service_compatibility.md
      - Twines: core_concepts/twines.md
      - core_concepts/twine_file_quickstart.md
  - glossary.md
  - license.md
  - version_history.md
  - support.md

theme:
  name: material
  logo: images/logos_square-dark.png
  favicon: images/logos_square-dark.png

  features:
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.copy

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - privacy
  - glightbox
  - search

copyright: Copyright &copy; 2025 Octue

extra:
  social:
    - icon: material/github
      link: https://github.com/octue
    - icon: material/linkedin
      link: https://www.linkedin.com/company/octue
    - icon: material/web
      link: https://octue.com

extra_css:
  - stylesheets/extra.css
